### ISSUE TITLE
GBM roadmap, todo list and issue list

### ISSUE THREAD

**Issue by lrusak** [xbmc/xbmc#14876]
# Roadmap

GBM windowing (DRM/KMS) in Kodi aims to be the best form of windowing for use in a single application/fullscreen environment setting using either GL or GLES. To achieve this we want to be able to stay on top of the latest technologies available and be on the forefront of upcoming technologies.

 - [x] refresh rate switching
 - [x] atomic modesetting
 - [x] headless support
 - [x] 10 bit support
 - [ ] HDR support
 - [ ] multi screen support
 - [ ] multi gpu support

# TODO

 - add the ability to take a screenshot when playing a video with direct to plane rendering (depends on #14091)
 - allow setting drm properties for color range and color space (underway #14358)
 - add vt handler to allow better setup of kodi:
   - make sure the vt is not already in graphics mode (another display server may be running)
   - automatically switch to a free vt (and back when exiting Kodi)
   - allow switching away from the Kodi vt and back without exiting Kodi.
 - cleanup and make uniform debug logging within `windowing/gbm`
 - add `README.md` in windowing/gbm to provide documentation about GBM windowing (and DRM/KMS)
 - add doxygen information to headers in `windowing/gbm`
 - add multi monitor support
 - add multi gpu support

# Issues

 - no input if not in the applicable `input` group (partially fixed by: #14873)
 - Kodi segfaults if started from an x11/wayland session

**Comment by lrusak** [comment]
Updated to track some changes that have merged.

**Comment by graysky2** [comment]
I see this hasn't been updated in a few years.  I understood that gbm now support HDR and 10bit video.  Is that true?

**Comment by bam80** [comment]
>  multi screen support
multi gpu support

For these, wouldn't it be better to rely on Wayland compositors, as a huge work on the matter is going on in there?
I can say on behalf of KWin, at least.

**Comment by lrusak** [comment]
> >  multi screen support
> 
> multi gpu support
> 
> 
> 
> For these, wouldn't it be better to rely on Wayland compositors, as a huge work on the matter is going on in there?
> 
> I can say on behalf of KWin, at least.

This is specific to GBM windowing, not Wayland.

**Comment by bam80** [comment]
Still, why to even bother try to solve a huge multi screen/multi gpu support task on GBM level if it's already being solved on Wayland?
It sounds like trying to reinvent the wheel and break the neck along the way.

**Comment by lrusak** [comment]
> Still, why to even bother try to solve a huge multi screen/multi gpu support task on GBM level if it's already being solved on Wayland?
> 
> It sounds like trying to reinvent the wheel and break the neck along the way.

Because we don't need to run a compositor?

I'm not actively working on either of these items. They were just ideas when I originally made the list.

**Comment by bam80** [comment]
> Because we don't need to run a compositor?

I believe we do need it as soon as we want to solve the two specific tasks (multi screen/multi gpu support) for good.

> I'm not actively working on either of these items. They were just ideas when I originally made the list.

Me neither. Just my 2 cents.

**Comment by jsumners** [comment]
I hope this one gets solved: 

> allow switching away from the Kodi vt and back without exiting Kodi.

**Comment by ccope** [comment]
just wanted to say I'm using GBM on Linux now to have working HDR, which is not currently supported by Wayland or X11. thanks for all your hard work @lrusak (and others)!

**Comment by chewitt** [comment]
> wouldn't it be better to rely on Wayland compositors, as a huge work on the matter is going on in there?

Wayland does not support dynamic refresh rate switching. Until that changes there's a strong case for having features that aren't dependent on Wayland.

**Comment by bam80** [comment]
> Wayland does not support dynamic refresh rate switching. Until that changes there's a strong case for having features that aren't dependent on Wayland.

Then, change that is the better point to apply the efforts.
Maybe we need special Wayland protocol for that. Need to sit together and decide.

Having that, I think there is no as strong cases of duplicating features present in the compositors.

**Comment by chewitt** [comment]
> Then, change that is the better point to apply the efforts.

My long-time understanding is that Wayland devs dismissed the idea, but that's second/third-hand info and I couldn't point you to records of discussions. Hopefully I'm wrong :)

**Comment by toupeira** [comment]
My own limited understanding is that refresh rate switching might come as part of https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/69 some day, but there hasn't been much progress in years (but Wayland is ready, they keep telling us :grin:).

**Comment by bam80** [comment]
> but there hasn't been much progress in years (but Wayland is ready, they keep telling us 😁).

Not a years actually but maybe Kodi needs to step in as an interested party, to speed it up?
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/44
https://invent.kde.org/plasma/kwin/-/issues/85

**Comment by popcornmix** [comment]
VRR is an optional feature of HDMI 2.1b and isn't widely supported.
So a VRR solution under wayland isn't going to be of much use to the majority of kodi users,
who just want the traditional switching between different refresh rates.

**Comment by bam80** [comment]
Then, it can be another protocol with the functions the majority would need.
Wayland was designed to be expandable so I see no obstacles.

But I think it's in major our responsibility, there is no point to wait for someone to do the staff you need.

**Comment by popcornmix** [comment]
See: https://github.com/xbmc/xbmc/issues/20614 where a wayland dev says:

> Wayland doesn't allow clients to change the refresh rate of the output. This is by design.

**Comment by bam80** [comment]
Our case seems also described here:

> Fixed framerate content

> A video player is fullscreen. It displays a video which has a fixed 25Hz framerate. In addition to this, either:
> 
>  -   The output has a 25Hz mode available, and the compositor is willing to perform a modeset.
>  -   The output supports VRR, e.g. with a 35Hz-60Hz range. The compositor is willing to page-flip at 50Hz (double the video framerate).
> 
> Without knowing the video framerate, the compositor can't do any of this. This results in frames being displayed at the wrong time, or this forces the video player to unnecessarily perform frame interpolation.

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/22#fixed-framerate-content

**Comment by tamodolo** [comment]
> VRR is an optional feature of HDMI 2.1b and isn't widely supported. So a VRR solution under wayland isn't going to be of much use to the majority of kodi users, who just want the traditional switching between different refresh rates.

This may be the case now but VRR is a feature that is slowly getting over mainstream now. Also, the desire of refresh rate change comes by wanting even cadence for 24Hz content. This is a specific feature for native 120Hz TVs that commonly also supports VRR. Only very old TVs will have some sort of "cinema mode" for 24Hz content to be even cadenced like old 3D TVs that are native 120Hz panels but don't expose it to HDMI signaling and solve that with internal detection algos.

VRR support is a feature very much needed at this point of time.

**Comment by aktau** [comment]
On the topic of HDR (currently marked as done), I surmise (also from experimentation) that this only works if GBM is combined with the GLES renderer (see e.g. #24160 and https://www.reddit.com/r/linux/comments/1atnp5k/hdr_and_intel/), as opposed to the OpenGL renderer a number of distros use as the default.

Would it be possible for the OpenGL renderer to also allow HDR? If so, I'd create an issue for tracking this, I wasn't able to find one. The reason I ask is that (for example) the Debian kodi package uses the OpenGL renderer [^1]. If the answer is "no" or "sure, but the GLES backend is the one we recommend", then I would lobby for distributions to compile with the GLES backend whenever possible.

[^1]: Except on Android, where it uses GLES: https://sources.debian.org/src/kodi/2%3A21.2%2Bdfsg-1/debian/rules/#L89.

**Comment by popcornmix** [comment]
You mean like https://github.com/xbmc/xbmc/pull/26406 ?

**Comment by aktau** [comment]
> You mean like https://github.com/xbmc/xbmc/pull/26406 ?

Yes, exactly like that. I think my searches only used "OpenGL" instead of "GL". Sorry for not finding it and causing noise.

**Comment by KOPRajs** [comment]
> allow switching away from the Kodi vt and back without exiting Kodi

Actually, this would be a game changer for Wayland users. Instead of switching between the desktop and a fullscreen Kodi window, the user would be switching between Wayland desktop and the GBM Kodi. Also, it would allow you to run e.g. GBM Kodi on TTY1 and GBM RetroArch on TTY2 and switching between them without window manager. Or you could run a game in RetroArch from Kodi without the need to exit Kodi and restart it after the game.

**Comment by Voosjey** [comment]
It would also be interesting to integrate 2D support for 3D films into the GBM, so that one can watch all their 3D films in 2D, or use the 3D capabilities of the TV.
