### ISSUE TITLE
Internal add-on updates for Nexus

### ISSUE THREAD

**Issue by lrusak** [xbmc/xbmc#22209]
This issue is to keep track of updating the internal add-ons for the Nexus release. I'm looking for others to help out here.

Some of these add-ons don't have other locations, in which I will go through and update them with NA.

The others we can check done if they are up to date. Others that need updating I'll try and make a note of and we can try and link PR's as they get updated.

Generated with:
```
ls -1 addons | sed 's/^\(.*\)$/- [ ] \1/'
```

`N/A` audioencoder.kodi.builtin.aac
`N/A` audioencoder.kodi.builtin.wma
- [x] [game.controller.default](https://github.com/kodi-game/controller-topology-project/tree/master/addons/game.controller.default) - `Needs Update`
- [x] [game.controller.keyboard](https://github.com/kodi-game/controller-topology-project/tree/master/addons/game.controller.keyboard) - `Needs Update`
- [ ] [game.controller.mouse](https://github.com/kodi-game/controller-topology-project/tree/master/addons/game.controller.mouse)
- [x] [game.controller.snes](https://github.com/kodi-game/controller-topology-project/tree/master/addons/game.controller.snes) - `Needs Update`

`N/A` kodi.binary.global.audioengine
`N/A` kodi.binary.global.filesystem
`N/A` kodi.binary.global.general
`N/A` kodi.binary.global.gui
`N/A` kodi.binary.global.main
`N/A` kodi.binary.global.network
`N/A` kodi.binary.global.tools
`N/A` kodi.binary.instance.audiodecoder
`N/A` kodi.binary.instance.audioencoder
`N/A` kodi.binary.instance.game
`N/A` kodi.binary.instance.imagedecoder
`N/A` kodi.binary.instance.inputstream
`N/A` kodi.binary.instance.peripheral
`N/A` kodi.binary.instance.pvr
`N/A` kodi.binary.instance.screensaver
`N/A` kodi.binary.instance.vfs
`N/A` kodi.binary.instance.videocodec
`N/A` kodi.binary.instance.visualization
`N/A` kodi.resource
- [ ] metadata.album.universal
- [ ] metadata.artists.universal
- [ ] metadata.common.allmusic.com
- [ ] metadata.common.fanart.tv
- [ ] metadata.common.musicbrainz.org
- [ ] metadata.common.theaudiodb.com
- [ ] metadata.demo.movies
- [ ] metadata.demo.tv
- [ ] [metadata.generic.albums](https://gitlab.com/ronie/metadata.generic.albums) - `Needs Update`
- [ ] [metadata.generic.artists](https://gitlab.com/ronie/metadata.generic.artists) - `Needs Update`
- [ ] metadata.local
- [ ] metadata.themoviedb.org.python
- [x] metadata.tvshows.themoviedb.org.python
- [ ] repository.xbmc.org
- [ ] resource.images.weathericons.default
- [ ] resource.language.en_gb
- [ ] resource.uisounds.kodi

`N/A` screensaver.xbmc.builtin.black
`N/A` screensaver.xbmc.builtin.dim
- [ ] script.module.pil
- [ ] script.module.pycryptodome
- [ ] service.xbmc.versioncheck
- [x] skin.estouchy - I think this is the master source?
- [x] skin.estuary - Not sure where the upstream is these days as https://github.com/xbmc/skin.estuary/ is old
- [ ] [webinterface.default](https://github.com/xbmc/chorus2) - looks like updates have been made but no new version

`N/A` xbmc.addon
`N/A` xbmc.core
`N/A` xbmc.gui
`N/A` xbmc.json
`N/A` xbmc.metadata
`N/A` xbmc.python
`N/A` xbmc.webinterface

**Comment by lrusak** [comment]
@garbear can you take care of the game controller add-ons?

@ronie can you take care of your add-ons?

**Comment by enen92** [comment]
There's nothing to do for estuary, upstream repo has been our master branch for a while now.

**Comment by garbear** [comment]
Done: https://github.com/xbmc/xbmc/pull/22219

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/pull/22235 for metadata.tvshows.themoviedb.org.python

**Comment by lrusak** [comment]
@ronie ping again for your add-ons, otherwise someone else may be able to do it.
